[json_data]
type = "service_account"
project_id = "ee-darlainedeme"
private_key_id = "66fa22239fd3d77757152008e225431727957764"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCV8xgOsMBL2WBL
mSTVfvDaWSMRMkuzk+u87sNM8pBSvxCcROG772SA6t+fUz/Kjxvunqfry2xaJL0x
75W3QGz/0UDhj6V27ZRUMxL7ebowH3m0aJbOZ8qVsjWRp80FzH2wBfJgODXcaJjU
ByW4/5W6q8xlVZG7f8bBNVbXxmSm41ZHBo1njSLBHFTO8t11Hcl2E5yWJJhVrmKU
5ZT4WhI022Y/5cfATUnRaRf47YcyUnkkDu5gmOV2eC7MJ/LASPPMZxlPuPx95oaJ
ZfzZU/AXd5TeiITrO8CLq955onyL9aqt477kqs3yPc/TqXKMtmD2ERzq5JQRYy8U
pg/MjdvHAgMBAAECggEABXebEXINWNagpbD8QFKECpoEZsycKPyENFvKQCR58aJo
wyHZzyXf1rl5lNAOu95y6MTdH4JHvZOoWElBfrB5KOyivnaj1E2+QkGoeAXMrZOA
Nv03PmhXYRTh0iE5nvQBQyk8WJjEEfi4Vca6799VwLwh1DIGAb2bbBD7TRu9ML57
7cdPGaMyHQ8d7oY9S2ARiPjdka2+QyPvuAZYhuNCoP5xj3rODyGMS/YiAyOSLjuD
81Fade77bSfRyb9JfN3fZA4394Q5oS54T3/gix3vG4oDaYYxCi4B2G18cQ7/lyIk
/JJN6WKuryZKeByKJe9b3LljjXOL2KLPGYc1zQ06CQKBgQDEPOqj4+MuuxCyVNNs
+7KpaVBxy5oTi2FK1OoHYMNODMLlWDZKoig+mHZIWo4Mn3zk02ax2+VhLtnpc7+0
AWF54LvdMSmd3xyx07Y3xnBlbalINmJL2REOscbs2vekvb5MjCRw2R7jMHmYB7+y
UByjPFzfH4sj3ghi0VBCHWeYqQKBgQDDnXLCJdXMWzGCDa73c9yyxHTmfNWgf0j7
r0M4m9f00opUPN9fxP8gKpmR7uBUFFcIagQFhvULhf+OTCHU/JNY7jp48nQI0Jh+
83vN93bvlnR4vTC3ISkjeaa2UMlOmsQheFXHP5qxua4wXHASJPn4bTxvM2u5/1Ll
8Hx/ZMtm7wKBgF8uGLSzNJ6W1utYH1At6KMo1H7NPQcbxG3SRUyczz3NDL7GgVbD
vfdWZZCEc3+F38LxEk9UE7aGTeVgYewB+3Bs41HOpZvP+o/52tjEpAFeJgxDbHvT
ZeWVrqF1N0YtTd683nPpq4SQH3nw0DbBipJWFcmW+BrGd5TOZzoaHwQ5AoGAFdSy
g/xY+e+LfOouBqvFi6XlLfvsk3bhHEWZCO5LkaUVjwUkILoJhvt6HBE+s+N5OxUp
0bwYCOsxdB4HAJAXmassl2bnkDxHaJOf04K0oVR3NypWD3oB71WaR2qIrN8U2G9n
k08D4qXITNlkIIJD63e1cOuaMC3QgJzwJ/+Fu70CgYBeRLL46f2IZQv5yW1hayl8
F4O7EjOS23iNo6yUVxbC5eR3KZDnDSulvlqrx2fk8yxAHl/ly7/W8FIExc8RgVSW
7UqptxYHwKGxzPlSKeSqGBD5cN8PIsZatsqngNBRurb7ExxfMxNWTXyhiESyQEG2
Vp39WgY54NER1/SedwzItQ==
-----END PRIVATE KEY-----
"""
client_email = "gisele@ee-darlainedeme.iam.gserviceaccount.com"
client_id = "117522661135205752748"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gisele%40ee-darlainedeme.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
